@host = http://127.0.0.1:9000
@lang = pt
@accesstoken = {{login.response.body.$.accesstoken}}
@id = {{create.response.body.$.id}}
@email = {{create.response.body.$.mail}}

###

# @name login
POST {{host}}/auth?lang={{lang}} HTTP/1.1
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "12345678"
}

###

# @name getAll
GET {{host}}/user?lang={{lang}}&page=1&limit=5&order=desc&sort=updated_at HTTP/1.1
Authorization: Bearer {{accesstoken}}

###

# @name getByID
GET {{host}}/user/{{id}}?lang={{lang}} HTTP/1.1
Authorization: Bearer {{accesstoken}}

###

# @name create
POST {{host}}/user?lang={{lang}} HTTP/1.1
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{
  "email": "user@created.com",
  "name": "User Created",
  "profile_id": 1,
  "status": true
}

###

# @name updateByID
PUT {{host}}/user/{{id}}?lang={{lang}} HTTP/1.1
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{
  "email": "user@updated.com",
  "name": "User Updated",
  "profile_id": 1,
  "status": false
}

###

# @name setUserPassword
PATCH {{host}}/user/{{email}}/passw?lang={{lang}} HTTP/1.1
Authorization: Bearer {{accesstoken}}
Content-Type: application/json

{
  "password": "secret",
  "password_confirm": "secret"
}

###

# @name resetUserPassword
PATCH {{host}}/user/{{id}}/reset?lang={{lang}} HTTP/1.1
Authorization: Bearer {{accesstoken}}

###

# @name deleteByID
DELETE {{host}}/user/{{id}}?lang={{lang}} HTTP/1.1
Authorization: Bearer {{accesstoken}}