version: '3.1'

name: go-template

volumes:

  go_template_postgre_volume:
    name: go_template_postgre_volume

networks:

  go_template_network:
    name: go_template_network
    driver: bridge

services:

  postgres:

    hostname: postgres
    container_name: postgres
    image: postgres:14.7-alpine
    restart: always
    volumes:
      - go_template_postgre_volume:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_BASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    networks:
      - go_template_network

  backend:

    container_name: backend
    build: .
    image: backend:0.0.6
    restart: always
    depends_on:
      - postgres
    ports:
      - ${API_PORT}:${API_PORT}
    tty: true
    environment:
      - TZ=${TZ}
    networks:
      - go_template_network