name: go-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  Test:
    name: Golang test

    runs-on: [ubuntu-latest]

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false

      - name: Run Test
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: go test ./...
